//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionTime
    {
        public decimal code { get; set; }
        public Nullable<decimal> businessCode { get; set; }
        public Nullable<decimal> day { get; set; }
        public Nullable<decimal> time { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Times Times { get; set; }
    }
}
