//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business()
        {
            this.ActionTime = new HashSet<ActionTime>();
            this.ActionToBusiness = new HashSet<ActionToBusiness>();
            this.AddCancelTime = new HashSet<AddCancelTime>();
            this.Cancellation = new HashSet<Cancellation>();
            this.ClientToBusiness = new HashSet<ClientToBusiness>();
            this.ClientToBusiness1 = new HashSet<ClientToBusiness>();
        }
    
        public decimal code { get; set; }
        public string businessName { get; set; }
        public string description { get; set; }
        public string logo { get; set; }
        public string fontColor { get; set; }
        public string backGroundColor { get; set; }
        public string tableColor { get; set; }
        public string freeTurnColor { get; set; }
        public string takenTurnColor { get; set; }
        public string cancelledTurnColor { get; set; }
        public string street { get; set; }
        public string numHouse { get; set; }
        public string city { get; set; }
        public Nullable<decimal> experience { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<decimal> minDurationTurn { get; set; }
        public Nullable<decimal> rangeEnablingTurn { get; set; }
        public string password { get; set; }
        public string ownerName { get; set; }
        public Nullable<bool> completeRegistration { get; set; }
        public Nullable<decimal> maxTurnstoClient { get; set; }
        public string clientCancellationsColor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionTime> ActionTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionToBusiness> ActionToBusiness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddCancelTime> AddCancelTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancellation> Cancellation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientToBusiness> ClientToBusiness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientToBusiness> ClientToBusiness1 { get; set; }
    }
}
