//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QmaticEntities2 : DbContext
    {
        public QmaticEntities2()
            : base("name=QmaticEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionTime> ActionTime { get; set; }
        public virtual DbSet<ActionToBusiness> ActionToBusiness { get; set; }
        public virtual DbSet<AddCancelTime> AddCancelTime { get; set; }
        public virtual DbSet<Business> Business { get; set; }
        public virtual DbSet<Cancellation> Cancellation { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ClientToBusiness> ClientToBusiness { get; set; }
        public virtual DbSet<Holidays> Holidays { get; set; }
        public virtual DbSet<Times> Times { get; set; }
        public virtual DbSet<Turns> Turns { get; set; }
    }
}
