//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turns
    {
        public decimal code { get; set; }
        public string clientId { get; set; }
        public Nullable<decimal> businessCode { get; set; }
        public Nullable<System.DateTime> turnDate { get; set; }
        public Nullable<System.TimeSpan> hour { get; set; }
        public Nullable<decimal> codeAction { get; set; }
    
        public virtual ActionToBusiness ActionToBusiness { get; set; }
        public virtual ClientToBusiness ClientToBusiness { get; set; }
    }
}
